classDiagram
    direction TB

%% ══════════════════════════════════════════
%% Policy domain:
%% Updated Policy Domain design for V2
%% ══════════════════════════════════════════

    namespace Domain_Policy {
        class PurchasePolicy
        class DiscountPolicy
        class PolicyScope
        class Discount
        class DiscountSummary
        class PolicyBuilder
        class PolicyValidationResult
        class PurchaseContext
        class IPolicy
        class IBasicPolicy
        class ICompositePolicy
        class ConcreteBasicPolicy
        class ConcreteCompositePolicy
    }

    %% ══════════════════════════════════════════
    %% AGGREGATE DiscountPolicy:
    %% Checks IPolicies and if eligible returns discount Amount based on Discounts
    %% ══════════════════════════════════════════

    class DiscountPolicy {
        <<Aggregate Root>>
        - DiscountPolicyId id
        - CompanyId companyId
        - PolicyScope scope
        - List~Discount~ discounts
        - boolean stackable
        - boolean active
        + activate() void
        + deactivate() void
        + setScope(PolicyScope) void
        + allowStacking() void
        + disallowStacking() void
        + setCompanyWide() void
        + setNotCompanyWide() void
        + addEvent(EventId) void
        + removeEvent(EventId) void
        + getFullDiscountSummary(PurchaseContext, Money) DiscountSummary
        + isPurchaseEligibleForDiscount(PurchaseContext) boolean
        + generateDiscountSnapshot(PurchaseContext context, Money baseCost) DiscountSnapshot
    }

    %% ══════════════════════════════════════════
    %% AGGREGATE PurchasePolicy:
    %% Checks IPolicies and if not eligible returns false (can return PolicyValidationResult)
    %% ══════════════════════════════════════════
    class PurchasePolicy {
        <<Aggregate Root>>
        - PurchasePolicyId id
        - CompanyId companyId
        - PolicyScope scope
        - IPolicy policy
        + isAllowedContext(PurchaseContext) boolean
        + requirePurchasePolicy(PurchaseContext) void
        + evaluate(PurchaseContext) PolicyValidationResult
    }

    class PolicyScope {
        <<Value Object>>
        - boolean companyWide
        - Set<EventId> eventIds
        + appliesTo(EventId) boolean
    }

    class Discount {
        <<Entity>>
        - String name
        - BigDecimal discountPercent
        - IPolicy policy
        + isEligible(PurchaseContext) boolean
        + getEligibleDiscountPercent(PurchaseContext) BigDecimal
    }

    class DiscountSummary {
        <<Value Object>>
        - List~String~ appliedDiscountsNames
        - List~BigDecimal~ appliedDiscountsPercents
        - List~BigDecimal~ actualDiscountAmount
        - BigDecimal totalDiscount
    }
        
    class PolicyValidationResult {
        <<Value Object>>
         - boolean valid
         - String reason
         + isSuccess() boolean
         + failureReason() Optional~String~
    }


    class PurchaseContext {
        <<Value Object>>
        - EventId eventId
        - CompanyId companyId
        - List~ZoneId~ zoneOfEachTicket
        - LocalDate buyerBirthdate
        - String code
    }

    %% ══════════════════════════════════════════
    %% Main Concept: Strategy + Compositon
    %% IPolicy validate/require some condition
    %% Basic policies used in strategy pattern across policies
    %% Composite policies are composed of other policies
    %% ══════════════════════════════════════════
    class IPolicy {
        <<interface>>
        + validate(PurchaseContext) boolean
        + require(PurchaseContext) void
        + isValidPolicy() boolean
    }

    class PolicyBuilder {
        <<Domain Service>>
        - List~IPolicy~ policies
        + add(IPolicy) PolicyBuilder
        + build() IPolicy
    }

    class IBasicPolicy {
        <<interface>>
        + isComposite() boolean
        + isValidPolicy() boolean
    }

    class ICompositePolicy {
        <<interface>>
        + children() List~IPolicy~
        + isComposite() boolean
        + isValidPolicy() boolean
    }

    class ConcreteBasicPolicy {
        <<Basic Policy Implementations>>
        MinAgePolicy
        CodePolicy
        DatePolicy
        TicketAmountPolicy
        AlwaysTruePolicy
        NeverAllowPolicy
    }

    class ConcreteCompositePolicy {
        <<Composite Policy Implementations>>
        AndPolicy
        OrPolicy
        ZoneSpecificPolicy
    }

    PurchasePolicy"1" *-- "1" PolicyScope : defines policy scope
    PurchasePolicy"1" *-- "1" IPolicy : defines policy conditions
    PurchasePolicy ..> PolicyValidationResult

    DiscountPolicy"1" *-- "1" PolicyScope : defines policy scope
    DiscountPolicy"1" *-- "1..n" Discount
    DiscountPolicy ..> PurchaseContext
    DiscountPolicy ..> DiscountSummary

    Discount "1"*--"1" IPolicy : defines discount conditions
    Discount ..> PurchaseContext

    PolicyBuilder "1" o-- "0..n" IPolicy : collects rules
    PolicyBuilder ..> IPolicy : builds rule tree

    IPolicy <|-- IBasicPolicy
    IPolicy <|-- ICompositePolicy

    IBasicPolicy <|.. ConcreteBasicPolicy

    ICompositePolicy "1" o-- "1..n" IPolicy : children policies
    ICompositePolicy <|.. ConcreteCompositePolicy



%%External files:
    namespace Domain_Company {
        class CompanyId
    }

    namespace Domain_Event {
        class EventId
        class ZoneId
    }
 

%%External relations:
    PurchasePolicy ..> CompanyId : owner company  id
    DiscountPolicy ..> CompanyId : owner company  id 
    PolicyScope"1" --> "0..n" EventId
    PurchaseContext ..> CompanyId : purchased event's companyId
    PurchaseContext ..> EventId :  purchased event's eventId
    PurchaseContext ..> ZoneId :  purchased event ticket zone ids


%%Repository Connection Example
    
    namespace Infrastructure_Persistence {
        class PurchasePolicyRepository
        class DiscountPolicyRepository
    }

    class PurchasePolicyRepository {
        <<Repository>>
        -ConcurrentMap~PurchasePolicyId, PurchasePolicy~ policies
    }

    class DiscountPolicyRepository {
        <<Repository>>
        -ConcurrentMap~DiscountPolicyId, DiscountPolicy~ policies
    }

    PurchasePolicyRepository ..> PurchasePolicy : Manages persistence
    DiscountPolicyRepository ..> DiscountPolicy : Manages persistence


    

